---
# Playbook que hace el despliegue de la configuracion
# Cuando corresponda activar el rol "firewall"

# Base
- name: Instalacion Zabbix Agent
  hosts: all
  vars_files:
    - vars/common.yml
  user: cchacoff

  roles:
    - base
